CREATE DATABASE trabalho;
USE trabalho;


DROP TABLE IF EXISTS RESERVA;
DROP TABLE IF EXISTS QUARTO;
DROP TABLE IF EXISTS CLIENTE;


CREATE TABLE CLIENTE (
    CPF             VARCHAR(14)         NOT NULL,
    TELEFONE        VARCHAR(18)         NOT NULL,
    NOME            VARCHAR(200)        NOT NULL,
    EMAIL           VARCHAR(100)        NOT NULL,
    DATA_NASCIMENTO DATE                NOT NULL,
    CEP             VARCHAR(9)          NOT NULL,
    PRIMARY KEY (CPF)
);


CREATE TABLE QUARTO (
    NUM_QUARTO      INT                 NOT NULL,
    TIPO_QUARTO     VARCHAR(50)         NOT NULL,
    VALOR_DIARIA    DECIMAL(10, 2)      NOT NULL,
    LIMITE_PESSOAS  INT                 NOT NULL,
    CAFE_INCLUSO    INT                 NOT NULL DEFAULT 0,
    CPF             VARCHAR(14),
    PRIMARY KEY (NUM_QUARTO),
    FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF)
);


CREATE TABLE RESERVA (
    NUM_RESERVA         INT             NOT NULL,
    DATA_INICIO         DATE            NOT NULL,
    DATA_FINAL          DATE            NOT NULL,
    QUANTIDADE_PESSOAS  INT             NOT NULL,
    VALOR_RESERVA       DECIMAL(10, 2)  NOT NULL,
    CPF                 VARCHAR(14), 
    NUM_QUARTO          INT,
    PRIMARY KEY (NUM_RESERVA),
    FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF),
    FOREIGN KEY (NUM_QUARTO) REFERENCES QUARTO(NUM_QUARTO)
);
